Add missing dependencies
Fixing error in install hook:
ERROR: Could not find a version that satisfies the requirement hatch-vcs<0.6.0,>=0.4.0 (from versions: none)
ERROR: No matching distribution found for hatch-vcs<0.6.0,>=0.4.0

Closes-Bug: #2091295

Change-Id: Id83d99d8d549c7c1e9f0c0d5e158b9c709c27ba2
Signed-off-by: Jorge Merlino <jorge.merlino@canonical.com>